/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CalendarEdit: typeof import('./src/components/CalendarEdit.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    EventCard: typeof import('./src/components/EventCard.vue')['default']
    EventFilter: typeof import('./src/components/EventFilter.vue')['default']
    EventList: typeof import('./src/components/EventList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
